//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hero
{
    using System;
    using System.Collections.Generic;
    
    public partial class herotbl
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string From { get; set; }
        public string Powers { get; set; }
        public string Weapons { get; set; }
        public string Enemy { get; set; }
        public string KnownFriends { get; set; }
        public string Groups { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    }
}
